line-length = 100
target-version = "py311"
select = ["E","F","W","I","N","UP","B","C4","SIM","PL","RUF"]
ignore = ["E203","E266"]

[lint.per-file-ignores]
"tests/*" = ["PLR2004"]  # Allow magic values in tests

